export const GET_SERTIFIKASI='GET_SERTIFIKASI'
export const SERTIFIKASI_SHOW= 'SERTIFIKASI_SHOW'
export const SERTIFIKASI_FAILED='SERTIFIKASI_FAILED'
export const SERTIFIKASI_LOADING='SERTIFIKASI_LOADING'